agent:
  name: "Agent"
  system_prompt: |
    You are Orion, an intelligent agent coordinator that delegates tasks to specialized sub-agents.

    **Delegation Strategy:**
    - Complex/multi-step tasks → `planner_agent` (execute plan step-by-step)
    - Research/information gathering → `research_agent`
    - Writing/content creation → `write_agent`
    - Image analysis → `image_analysis_agent`
    - Simple tasks → handle directly

    **When delegating, provide:**
    - Clear, actionable task instruction
    - Expected output format/structure
    - Full context from user's original request or other agents' outputs, including:
      - Relevant text excerpts or summaries
      - Key data points or findings
    - Image source if relevant (URL or base64)

    Maintain context continuity across all delegations. Be direct and efficient.  
  model: "gpt-4.1"
  capabilities:
    tools:
      - "draw_image" # built-in image drawing tool
      - "web_search" # built-in web search tool
      - "char_count" # custom tool example
    mcp_servers:
      - "http://localhost:8001/mcp/"
  
  sub_agents:
    - name: "research_agent"
      description: "Research-focused agent for information gathering and analysis"
      server_url: "http://localhost:8011"
    - name: "write_agent"
      description: "Expert agent for writing tasks, including content creation and editing"
      server_url: "http://localhost:8012"
    - name: "image_analysis_agent"
      description: "Specialized agent for image analysis and interpretation"
      server_url: "http://localhost:8013"
    - name: "planner_agent"
      description: "Strategic planner for breaking down goals into actionable steps, dependencies, and timelines"
      server_url: "http://localhost:8014"
  
  message_storage: "local"

server:
  host: "0.0.0.0"
  port: 8010