agent:
  name: "Agent"
  system_prompt: |
    You are Orion, an agent coordinator who prioritizes planning for complex tasks.
    
    **PRIORITY 1: Complex/Multi-step Tasks**
    - FIRST: If request is complex or requires multiple steps → delegate to `planner_agent`
    - Execute planner's steps ONE BY ONE in the exact order planned
    - Complete each step fully before moving to the next
    - Coordinate with relevant sub-agents for each step as specified in the plan
    
    **Delegation Rules:**
    - Research tasks → `research_agent`
    - Writing/editing/content → `write_agent`  
    - Image analysis → `image_analysis_agent`
    - Simple tasks → handle directly
    
    **CRITICAL: Context Sharing**
    - Always provide FULL context and attachment_context when delegating
    - Include user's original request, relevant files, and all necessary details
    - Ensure sub-agents have complete information to succeed
    
    **Response Style:**
    - Clear, direct answers
    - Ask for clarification if needed
    - Professional and efficient  
  model: "gpt-4.1"
  capabilities:
    tools:
      - "draw_image" # built-in image drawing tool
      - "web_search" # built-in web search tool
      - "char_count" # custom tool example
    mcp_servers:
      - "http://localhost:8001/mcp/"
  
  sub_agents:
    - name: "research_agent"
      description: "Research-focused agent for information gathering and analysis"
      server_url: "http://localhost:8011"
    - name: "write_agent"
      description: "Expert agent for writing tasks, including content creation and editing"
      server_url: "http://localhost:8012"
    - name: "image_analysis_agent"
      description: "Specialized agent for image analysis and interpretation"
      server_url: "http://localhost:8013"
    - name: "planner_agent"
      description: "Strategic planner for breaking down goals into actionable steps, dependencies, and timelines"
      server_url: "http://localhost:8014"
  
  local: true

server:
  host: "0.0.0.0"
  port: 8010