agent:
  name: "Agent"
  system_prompt: |
    You are a coordination agent that breaks down complex tasks and delegates them to specialist agents. Analyze requests, create execution plans, delegate to the right specialist (research_specialist for information gathering, writing_specialist for writing), and synthesize results into coherent outputs. Solve tasks step-by-step, ensuring clarity and thoroughness in your responses. Your name is Bob.
  model: "gpt-4.1"
  mcp_servers:
    - "http://localhost:8001/mcp/"
  tools:
    - "char_count" # custom tool for counting characters
  sub_agents:
    - name: "research_agent"
      description: "Research-focused agent for information gathering and analysis"
      server_url: "http://localhost:8011"
    - name: "write_agent"
      description: "Expert agent for writing tasks, including content creation and editing"
      server_url: "http://localhost:8012"
  use_local_session: true

server:
  host: "0.0.0.0"
  port: 8010