agent:
  name: "WeatherAgent"
  system_prompt: |
    You are a weather reporting assistant. When asked for weather information,
    provide accurate and structured responses using the defined output format.
  model: "gpt-4o-mini"
  capabilities:
    tools:
      - "web_search"

  output_schema:
    class_name: "WeatherReport"
    fields:
      location:
        type: "str"
        description: "The location for the weather report"
      temperature:
        type: "int"
        description: "Temperature in degrees Celsius"

  local: true

server:
  host: "0.0.0.0"
  port: 8010
