import asyncio
import json
import logging
from typing import Any, Optional

from ..config import AgentConfig
from ..providers import MODEL_API_OPENAI_CHAT_COMPLETIONS, MODEL_API_OPENAI_RESPONSES, normalize_model_api
from .manager import ToolManager
from ...components import MessageStorageBase
from ...utils.image_utils import extract_source, is_image_output


logger = logging.getLogger(__name__)


class ToolExecutor:
    """Executes tool calls, handles image detection/captioning, and manages concurrent execution."""

    def __init__(
        self,
        tool_manager: ToolManager,
        message_storage: MessageStorageBase,
        client: Any,
        model_api: str = MODEL_API_OPENAI_CHAT_COMPLETIONS,
    ):
        self.tool_manager = tool_manager
        self.message_storage = message_storage
        self.client = client
        self.model_api = normalize_model_api(model_api)

    async def handle_tool_calls(
        self,
        tool_calls: list,
        input_messages: list,
        max_concurrent_tools: int = AgentConfig.DEFAULT_MAX_CONCURRENT_TOOLS,
    ) -> Optional[tuple[str, str]]:
        """
        Handle tool calls by executing them concurrently with concurrency limit.

        Returns:
            None if no image output, or (image_data, description) tuple.
        """
        if not tool_calls:
            return None

        function_calls = [tc for tc in tool_calls if self._tool_name(tc)]
        if not function_calls:
            return None

        is_responses_call = self._has_responses_replay_items(function_calls)
        if is_responses_call:
            input_messages.extend(self._responses_replay_items(function_calls))
        else:
            assistant_message = {
                "role": "assistant",
                "content": None,
                "tool_calls": [self._to_chat_tool_call(tc) for tc in function_calls],
            }
            reasoning_content = self._tool_reasoning_content(function_calls[0])
            if reasoning_content is not None:
                assistant_message["reasoning_content"] = reasoning_content
            content_blocks = self._tool_content_blocks(function_calls[0])
            if content_blocks is not None:
                assistant_message["content_blocks"] = content_blocks
            input_messages.append(assistant_message)

        semaphore = asyncio.Semaphore(max_concurrent_tools)

        async def execute_with_semaphore(tool_call):
            async with semaphore:
                return await self.execute_single(tool_call)

        tasks = [execute_with_semaphore(tc) for tc in function_calls]
        results = await asyncio.gather(*tasks)

        pending_images = []
        pending_descriptions = []

        for tool_message, image_data, description in results:
            input_messages.append(
                self._to_responses_tool_result(tool_message)
                if is_responses_call
                else tool_message
            )
            if image_data:
                pending_images.append(image_data)
            if description:
                pending_descriptions.append(description)

        if pending_images:
            return (
                "\n\n".join(pending_images),
                "\n\n".join(pending_descriptions),
            )

        return None

    async def execute_single(
        self,
        tool_call,
    ) -> tuple[dict, Optional[str], Optional[str]]:
        """Execute a single tool call and return (tool_message, image_data, description)."""
        name = self._tool_name(tool_call)
        call_id = self._tool_call_id(tool_call)
        raw_arguments = self._tool_arguments(tool_call)

        try:
            args = json.loads(raw_arguments or "{}")
        except Exception as e:
            logger.error("Tool args parse error: %s", e)
            return self._tool_result_message(call_id, f"Tool args parse error: {e}"), None, None

        if not isinstance(args, dict):
            return self._tool_result_message(call_id, "Tool args must be a JSON object."), None, None

        func = self.tool_manager.get_tool(name)
        if not func:
            return self._tool_result_message(call_id, f"Tool `{name}` not found."), None, None

        logger.info("Calling tool: %s with args: %s", name, args)

        try:
            result = await func(**args)
        except Exception as e:
            logger.error("Tool call error: %s", e)
            result = f"Tool error: {e}"

        result_str = json.dumps(result, ensure_ascii=False) if isinstance(result, (dict, list)) else str(result)

        image_data = None
        model_output = result_str
        if is_image_output(result_str):
            image_data = result_str
            image_src = extract_source(result_str)
            prompt_hint = args.get("prompt", "")
            caption = await self._caption_image(image_src, prompt_hint)
            model_output = (
                f"[Image generated by tool `{name}` and displayed to user. "
                f"Image description: {caption}]"
            )

        logger.info("Tool `%s` result: %s", name, self._format_preview(result_str))
        return self._tool_result_message(call_id, model_output), image_data, model_output if image_data else None

    async def _caption_image(self, image_data_uri: str, prompt_hint: str = "") -> str:
        """Use a vision model to generate a detailed description of an image."""
        caption_prompt = AgentConfig.IMAGE_CAPTION_PROMPT
        if prompt_hint:
            caption_prompt += f"\n\nOriginal generation prompt: \"{prompt_hint}\""

        try:
            if self.model_api == MODEL_API_OPENAI_RESPONSES:
                response = await self.client.responses.create(
                    model=AgentConfig.IMAGE_CAPTION_MODEL,
                    input=[{
                        "role": "user",
                        "content": [
                            {"type": "input_text", "text": caption_prompt},
                            {"type": "input_image", "image_url": image_data_uri},
                        ],
                    }],
                    store=False,
                )
                caption = self._extract_responses_caption(response)
                if caption.strip():
                    return caption.strip()

            response = await self.client.chat.completions.create(
                model=AgentConfig.IMAGE_CAPTION_MODEL,
                messages=[{
                    "role": "user",
                    "content": [
                        {"type": "text", "text": caption_prompt},
                        {"type": "image_url", "image_url": {"url": image_data_uri}},
                    ],
                }],
            )
            choices = getattr(response, "choices", []) or []
            message = getattr(choices[0], "message", None) if choices else None
            caption = getattr(message, "content", "") or ""
            if caption.strip():
                return caption.strip()
        except Exception as e:
            logger.warning("Image captioning failed, falling back to prompt-based description: %s", e)

        if prompt_hint:
            return f"Generated image based on prompt: \"{prompt_hint}\""
        return "An image was generated and displayed to the user."

    @staticmethod
    def _field(obj: Any, name: str, default: Any = None) -> Any:
        if isinstance(obj, dict):
            return obj.get(name, default)
        return getattr(obj, name, default)

    @classmethod
    def _tool_call_id(cls, tool_call) -> str:
        return cls._field(tool_call, "call_id") or cls._field(tool_call, "id") or "call_0"

    @classmethod
    def _tool_name(cls, tool_call) -> Optional[str]:
        name = cls._field(tool_call, "name")
        if name:
            return name
        function = cls._field(tool_call, "function") or {}
        return cls._field(function, "name")

    @classmethod
    def _tool_arguments(cls, tool_call) -> str:
        arguments = cls._field(tool_call, "arguments")
        if arguments is not None:
            return arguments
        function = cls._field(tool_call, "function") or {}
        return cls._field(function, "arguments") or "{}"

    @classmethod
    def _tool_reasoning_content(cls, tool_call) -> Optional[str]:
        return cls._field(tool_call, "reasoning_content")

    @classmethod
    def _tool_content_blocks(cls, tool_call) -> Optional[list[dict]]:
        return cls._field(tool_call, "content_blocks")

    @classmethod
    def _tool_response_items(cls, tool_call) -> Optional[list[dict]]:
        return cls._field(tool_call, "response_items")

    @classmethod
    def _has_responses_replay_items(cls, tool_calls: list) -> bool:
        return any(cls._tool_response_items(tool_call) for tool_call in tool_calls)

    @classmethod
    def _responses_replay_items(cls, tool_calls: list) -> list[dict]:
        for tool_call in tool_calls:
            response_items = cls._tool_response_items(tool_call)
            if response_items:
                return [dict(item) for item in response_items]
        return []

    @classmethod
    def _to_chat_tool_call(cls, tool_call) -> dict:
        return {
            "id": cls._tool_call_id(tool_call),
            "type": "function",
            "function": {
                "name": cls._tool_name(tool_call),
                "arguments": cls._tool_arguments(tool_call) or "{}",
            },
        }

    @staticmethod
    def _tool_result_message(call_id: str, content: str) -> dict:
        return {
            "role": "tool",
            "tool_call_id": call_id,
            "content": content,
        }

    @staticmethod
    def _to_responses_tool_result(tool_message: dict) -> dict:
        return {
            "type": "function_call_output",
            "call_id": tool_message.get("tool_call_id") or "call_0",
            "output": tool_message.get("content") or "",
        }

    @classmethod
    def _extract_responses_caption(cls, response: Any) -> str:
        output_text = cls._field(response, "output_text")
        if isinstance(output_text, str) and output_text:
            return output_text
        text_parts = []
        for output_item in cls._field(response, "output", []) or []:
            if cls._field(output_item, "type") != "message":
                continue
            for content_item in cls._field(output_item, "content", []) or []:
                text = cls._field(content_item, "text")
                if isinstance(text, str):
                    text_parts.append(text)
        return "".join(text_parts)

    @staticmethod
    def _format_preview(text: str) -> str:
        if len(text) <= AgentConfig.TOOL_RESULT_PREVIEW_LENGTH:
            return text
        return text[:AgentConfig.TOOL_RESULT_PREVIEW_LENGTH] + "..."
