agent:
  capabilities:
    mcp_servers:
    - http://localhost:8001/mcp/
    tools:
    - web_search
    - draw_image
    - char_count
  model: gpt-4.1-mini
  name: Agent
  system_prompt: "You are a helpful assistant. \n"
  use_local_session: true
server:
  host: 0.0.0.0
  port: 8010
