agent:
  name: "Agent"
  system_prompt: |
    You are a helpful assistant. 
  model: "gpt-4.1-mini"
  capabilities:
    tools:
      - "web_search" # built-in web search tool
      - "draw_image" # built-in image drawing tool
      - "char_count" # 自定义工具示例
    mcp_servers:
      - "http://localhost:8001/mcp/"
  
  use_local_session: true

server:
  host: "0.0.0.0"
  port: 8010