agent:
  name: "Agent"
  system_prompt: |
    You are a helpful assistant. Your task is to assist users with their queries and tasks.
  model: "gpt-4.1"

  capabilities:
    tools:
      - "web_search"  # Built-in web search
      - "draw_image"  # Built-in image generation (need set AWS credentials in .env)
      - "char_count"  # Custom tool for counting characters
      
  message_storage: "local"  # Use Redis for message storage currently supported  local or redis
  
server:
  host: "0.0.0.0"
  port: 8010