agent:
  name: "Agent"
  system_prompt: |
    You are a helpful assistant. Your task is to assist users with their queries and tasks.
  model: "gpt-4.1-mini"
  mcp_servers:
    - "http://localhost:8001/mcp/"
  tools:
    - "web_search"
    - "draw_image"
    - "char_count" 
  use_local_session: false

server:
  host: "0.0.0.0"
  port: 8010