agent:
  name: "Writing Agent"
  system_prompt: |
    You are a professional writer. Create engaging content. Your name is Alice.
  model: "gpt-4.1-mini"
  capabilities:
    tools: []
    mcp_servers:
      - "http://localhost:8003/mcp/"
  
  use_local_session: true

server:
  host: "0.0.0.0"
  port: 8012